### ISSUE TITLE
pfb_fhir config without a config creates a stack trace.

### ISSUE THREAD

**Issue by bwalsh** [bmeg/pfb_fhir#16]
$ pfb_fhir config
Traceback (most recent call last):
  File "/Users/walsbr/aced/data_model/venv/bin/pfb_fhir", line 8, in <module>
    sys.exit(cli())
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/pfb_fhir/cli.py", line 213, in config
    print(ctx.obj['model'].json())

**Comment by bwalsh** [comment]
Also

$ pfb_fhir config --format yaml
Traceback (most recent call last):
  File "/Users/walsbr/aced/data_model/venv/bin/pfb_fhir", line 8, in <module>
    sys.exit(cli())
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/walsbr/aced/data_model/venv/lib/python3.9/site-packages/pfb_fhir/cli.py", line 211, in config
    print(ctx.obj['model'].yaml())
AttributeError: 'Model' object has no attribute 'yaml'
